# Project information
site_name: 'SVG to PPT'
site_description: 'Official homepage of SVG to PPT'
site_url: 'https://blakegearin.github.io/svg-to-ppt'

# Repository
repo_name: blakegearin/svg-to-ppt
repo_url: https://github.com/blakegearin/svg-to-ppt
edit_uri: ''

nav:
  - Home: index.md
  - CLI: cli.md
  - Alfred: alfred.md

copyright: Copyright © 2021 Blake Gearin
extra:
  search:
    tokenizer: '[\s\-\.]+'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/blakegearin
    - icon: fontawesome/solid/home
      link: https://blakegearin.com

# Configuration
theme:
  name: 'material'
  custom_dir: 'theme'
  logo: 'img/svg-to-ppt-icon-transparent.svg'
  favicon: 'img/svg-to-ppt-icon.svg'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: 'en'
  font:
    text: 'Ubuntu'
    code: 'Roboto Mono'
  static_templates:
    - 404.html

extra_css:
  - stylesheets/colors.css

markdown_extensions:
- admonition
- footnotes
- pymdownx.superfences
- pymdownx.details
- toc:
    permalink: true
- codehilite:
    linenums: false
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
    options:
      attributes:
        width: 25px
