# This is a basic workflow to help you get started with Actions

name: application

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    - name: Latest tag
    # You may pin to the exact commit or the version.
    # uses: EndBug/latest-tag@6d22a6738f5c33059e3a8c6ca5dcf8eaf8a14599
    uses: EndBug/latest-tag@v1.4.0
    with:
      # Tag description
      description: # optional
      # Tag name
      tag-name: # optional, default is latest
